#!/bin/bash
set -e
if [[ ! -z "$DEBUG" ]]; then
  set -x
fi
trap "exit" INT

ROOT=$PWD
DIR=`dirname $(readlink $BASH_SOURCE || echo $BASH_SOURCE)`
if [[ "$1" == "push" ]]; then
  DO_PUSH=true
else
  DO_PUSH=false
  echo "  --- build-contract: Offline run (builds will not docker pull and image: will not be pushed) ---  "
fi

GIT_COMMIT=$(git rev-parse --verify --short HEAD 2>/dev/null)
if [[ ! -z "$GIT_COMMIT" ]]; then
  GIT_STATUS=$(git status -s)
  if [[ ! -z "$GIT_STATUS" ]]; then
    GIT_COMMIT="$GIT_COMMIT-dev"
  fi
  echo "This is a git repo and GIT_COMMIT=$GIT_COMMIT"
  export GIT_COMMIT
fi

# echo "In $(pwd) at $(date -Iseconds) on $(hostname)"

function wait_for_contract {
  sleep 3
  # Count the number of failed containers
  # NOTE: Assumes no other build contract process is running at the same time
  test_containers=$(docker ps -aq --filter label=com.yolean.build-contract)
  n_running_test_containers=$(docker ps -q --filter label=com.yolean.build-contract | wc -l)
  n_failures=$(docker inspect -f "{{.State.ExitCode}}" $test_containers | grep -v 0 | wc -l)

  if [[ $n_failures -gt 0 ]]; then
    # Build Contract Failed
    echo 1
  elif [[ $n_running_test_containers -eq 0 ]]; then
    # Build Contract Succeeded
    echo 0
  else
    # We're not done yet
    wait_for_contract
  fi
}

# Perform tests
BUILD_FLAGS='';
if [[ $DO_PUSH == true ]]; then
  BUILD_FLAGS="$BUILD_FLAGS --pull";
fi

cd $ROOT/build-contracts/
for compose_file in $(ls | grep .yml); do
  echo "  --- build-contract: $compose_file ---  "
  docker_compose="docker-compose -f $compose_file"
  $docker_compose rm -f
  $docker_compose build $BUILD_FLAGS
  $docker_compose up --force-recreate -d
  $docker_compose logs -f &
  bar=$(wait_for_contract)
  echo "Build Contract finished with $bar"
  $docker_compose kill
  if [[ $bar -ne 0 ]]; then
    echo "ERROR: Build Contract $compose_file failed, please see logs above for details"
    echo "ERROR: Aborting build!"
    exit $bar
  fi
done

echo "  --- build-contract: Build Contract finished. ---  "

# Push targets
for compose_file in $(ls | grep .yml); do
  echo "  --- build-contract: $compose_file ---  "
  docker_compose="docker-compose -f $compose_file"
  targets="$(cat $compose_file | $DIR/parsetargets)"
  for target in $targets; do
    echo "  --- build-contract: Found target \"$target\" ---  "
    if [[ $DO_PUSH == true ]]; then
      echo "  --- build-contract: Pushing target $target ---  "
      $docker_compose push $target
    fi
  done
done
