version: "2.1"
services:
  build-contract:
    image: localhost:5000/yolean/build-contract:${PUSH_TAG:-dev}
    build:
      context: ../
    labels:
    - com.yolean.build-target

  unittest:
    build:
      context: ../
      dockerfile: ./build-contracts/unittest/Dockerfile
    labels:
    - com.yolean.build-contract

  nginx:
    image: nginx

  client:
    build: ./client
    environment:
      TEST_EXIT_CODE: ${TEST_EXIT_CODE:-0}
    labels:
    - com.yolean.build-contract
