#!/bin/bash
set -e

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

$SCRIPTPATH/build-contract-predockerbuild

cd npm-monorepo/ci
npm install --production --package-lock-only --ignore-scripts
echo "------- packagelock details -------"
cat ../../npm-monorepo/ci/package.json
echo ""
shasum -a 256 ../../npm-monorepo/ci/npm-monorepo/* || echo "The module has no monorepo deps"
echo "------- packagelock details -------"
mv package-lock.json ../../
cd ../../
